INSERT OR REPLACE INTO settings (key, value) VALUES ('pool_size', '30');
INSERT OR REPLACE INTO settings (key, value) VALUES ('theme', 'system');
INSERT OR REPLACE INTO settings (key, value) VALUES ('tz', 'Asia/Manila');
INSERT OR REPLACE INTO settings (key, value) VALUES ('gcash_name', 'David Wings and Cafe');
INSERT OR REPLACE INTO settings (key, value) VALUES ('gcash_qr', '');
INSERT OR REPLACE INTO settings (key, value) VALUES ('contact', 'PUP Sta. Mesa, Manila · facebook.com/PUPDavidsWingsandCafe');
INSERT OR REPLACE INTO settings (key, value) VALUES ('flavors', '["Buffalo","Garlic Parmesan","Soy Garlic","Honey Butter","Salted Egg"]');
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (1, 'Boneless 6pcs', 'Wings', 119, 1, 1, 0);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (2, 'Boneless 12pcs', 'Wings', 219, 1, 1, 1);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (3, 'Boneless 18pcs', 'Wings', 319, 1, 1, 2);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (4, 'Wings Solo', 'Combos', 159, 1, 1, 3);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (5, 'Wings Duo', 'Combos', 289, 1, 1, 4);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (6, 'Barkada Box', 'Combos', 429, 1, 1, 5);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (7, 'Plain Rice', 'Sides', 20, 0, 1, 6);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (8, 'Fries', 'Sides', 59, 0, 1, 7);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (9, 'Cheesy Fries', 'Sides', 79, 0, 1, 8);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (10, 'Coleslaw', 'Sides', 39, 0, 1, 9);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (11, 'Iced Tea', 'Drinks', 35, 0, 1, 10);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (12, 'Soda', 'Drinks', 40, 0, 1, 11);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (13, 'Bottled Water', 'Drinks', 20, 0, 1, 12);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (14, 'Iced Americano', 'Drinks', 70, 0, 1, 13);
INSERT OR REPLACE INTO menu_items (id, name, category, price, flavored, available, sort) VALUES (15, 'Café Latte', 'Drinks', 85, 0, 1, 14);
